stages:
  - test
  - build
  - deploy

# Test stage (adjust if you have actual tests)
test:
  image: node:18
  stage: test
  script:
    - echo "Installing dependencies..."
    - npm ci
    - echo "Running tests (customize this step for your needs)..."
    - echo "No automated tests for static site; skipping."
  only:
    - main

# Build stage
build:
  image: node:18
  stage: build
  script:
    - echo "Installing dependencies and building project..."
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist
  only:
    - main

# Deploy stage using GitLab Pages
pages:
  stage: deploy
  script:
    - echo "Copying built files to public/ for GitLab Pages..."
    - mkdir -p public
    - cp -r dist/* public/
  artifacts:
    paths:
      - public
  only:
    - main